name: Run Python Script

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Set up uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync

      - name: Run Python script
        run: uv run python get_deadlines.py

      - name: Commit and push changes
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add output.ics
          if ! git diff-index --quiet HEAD; then
            git commit -m "Update by GitHub Action"
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
